--- #YAML:1.0
name: Posy-Plugin-MultiHeader
version: 0.02
author:
  - Kathryn Andersen
abstract: Posy plugin to enable multiple header templates.
license: perl
requires:
  Posy: 0.95
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::MultiHeader:
    file: lib/Posy/Plugin/MultiHeader.pm
    version: 0.02
generated_by: Module::Build version 0.261
