---
name: Posy-Plugin-MultiHeader
version: 0.03
author:
  - Kathryn Andersen
abstract: Posy plugin to enable multiple header templates.
license: perl
requires:
  Posy: 0.98
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::MultiHeader:
    file: lib/Posy/Plugin/MultiHeader.pm
    version: 0.03
generated_by: Module::Build version 0.2611
